const GET_PROVINCE_REQUEST = 'GET_PROVINCE_REQUEST';
const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS';
const GET_PROVINCE_FAIL = 'GET_PROVINCE_FAIL';

const GET_DISTRICT_REQUEST = 'GET_DISTRICT_REQUEST';
const GET_DISTRICT_SUCCESS = 'GET_DISTRICT_SUCCESS';
const GET_DISTRICT_FAIL = 'GET_DISTRICT_FAIL';

const GET_WARD_REQUEST = 'GET_WARD_REQUEST';
const GET_WARD_SUCCESS = 'GET_WARD_SUCCESS';
const GET_WARD_FAIL = 'GET_WARD_FAIL';
export default {
  GET_PROVINCE_REQUEST,
  GET_PROVINCE_SUCCESS,
  GET_PROVINCE_FAIL,
  GET_DISTRICT_REQUEST,
  GET_DISTRICT_SUCCESS,
  GET_DISTRICT_FAIL,
  GET_WARD_REQUEST,
  GET_WARD_SUCCESS,
  GET_WARD_FAIL,
};
