export const CREATE_BANK_NEW_REQUEST = 'CREATE_BANK_NEW_REQUEST';
export const CREATE_BANK_NEW_SUCCESS = 'CREATE_BANK_NEW_SUCCESS';
export const CREATE_BANK_NEW_FAIL = 'CREATE_BANK_NEW_FAIL';

export const GET_BANK_REQUEST = 'GET_BANK_REQUEST';
export const GET_BANK_SUCCESS = 'GET_BANK_SUCCESS';
export const GET_BANK_FAIL = 'GET_BANK_FAIL';
export const GET_BANKS_REQUEST = 'GET_BANKS_REQUEST';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';
export const GET_BANKS_FAIL = 'GET_BANKS_FAIL';
export const GET_BRANCH_REQUEST = 'GET_BRANCH_REQUEST';
export const GET_BRANCH_SUCCESS = 'GET_BRANCH_SUCCESS';
export const GET_BRANCH_FAIL = 'GET_BRANCH_FAIL';