export const CREATE_BANK_NEW_REQUEST = 'CREATE_BANK_NEW_REQUEST';
export const CREATE_BANK_NEW_SUCCESS = 'CREATE_BANK_NEW_SUCCESS';
export const CREATE_BANK_NEW_FAIL = 'CREATE_BANK_NEW_FAIL';

export const GET_LIST_BANK_REQUEST = 'GET_LIST_BANK_REQUEST';
export const GET_LIST_BANK_SUCCESS = 'GET_LIST_BANK_SUCCESS';
export const GET_LIST_BANK_FAIL = 'GET_LIST_BANK_FAIL';