export const SAVE_PRODUCT_CART_REQUEST = 'SAVE_PRODUCT_CART_REQUEST';
export const SAVE_PRODUCT_CART_SUCCESS = 'SAVE_PRODUCT_CART_SUCCESS';
export const SAVE_PRODUCT_CART_FAIL = 'SAVE_PRODUCT_CART_FAIL';

export const GET_PRODUCT_CART_REQUEST = 'GET_PRODUCT_CART_REQUEST';
export const GET_PRODUCT_CART_SUCCESS = 'GET_PRODUCT_CART_SUCCESS';
export const GET_PRODUCT_CART_FAIL = 'GET_PRODUCT_CART_FAIL';


export const DELETE_PRODUCT_CART_REQUEST = 'DELETE_PRODUCT_CART_REQUEST';
export const DELETE_PRODUCT_CART_SUCCESS = 'DELETE_PRODUCT_CART_SUCCESS';
export const DELETE_PRODUCT_CART_FAIL = 'DELETE_PRODUCT_CART_FAIL';

export const UPDATE_PRODUCT_CART_REQUEST = 'UPDATE_PRODUCT_CART_REQUEST';
export const UPDATE_PRODUCT_CART_SUCCESS = 'UPDATE_PRODUCT_CART_SUCCESS';
export const UPDATE_PRODUCT_CART_FAIL = 'UPDATE_PRODUCT_CART_FAIL';
