export const CATEGORY_SAVE_REQUEST = 'CATEGORY_SAVE_REQUEST';
export const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS';
export const CATEGORY_SAVE_FAIL = 'CATEGORY_SAVE_FAIL';

export const GET_CATEGORY_ALL_REQUEST = 'GET_CATEGORY_ALL_REQUEST';
export const GET_CATEGORY_ALL_SUCCESS = 'GET_CATEGORY_ALL_SUCCESS';
export const GET_CATEGORY_ALL_FAIL = 'GET_CATEGORY_ALL_FAIL';

export const REMOVE_CATEGORY_ADMIN_REQUEST = 'REMOVE_CATEGORY_ADMIN_REQUEST';
export const REMOVE_CATEGORY_ADMIN_SUCCESS = 'REMOVE_CATEGORY_ADMIN_SUCCESS';
export const REMOVE_CATEGORY_ADMIN_FAIL = 'REMOVE_CATEGORY_ADMIN_FAIL';