export const CATEGORY_SAVE_REQUEST = 'CATEGORY_SAVE_REQUEST';
export const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS';
export const CATEGORY_SAVE_FAIL = 'CATEGORY_SAVE_FAIL';

export const GET_CATEGORY_ALL_REQUEST = 'GET_CATEGORY_ALL_REQUEST';
export const GET_CATEGORY_ALL_SUCCESS = 'GET_CATEGORY_ALL_SUCCESS';
export const GET_CATEGORY_ALL_FAIL = 'GET_CATEGORY_ALL_FAIL';

export const UPDATE_STATUS_CATEGORY_REQUEST = 'UPDATE_STATUS_CATEGORY_REQUEST';
export const UPDATE_STATUS_CATEGORY_SUCCESS = 'UPDATE_STATUS_CATEGORY_SUCCESS';
export const UPDATE_STATUS_CATEGORY_FAIL = 'UPDATE_STATUS_CATEGORY_FAIL';

export const GET_CATEGORY_ADMIN_REQUEST = 'GET_CATEGORY_ADMIN_REQUEST';
export const GET_CATEGORY_ADMIN_SUCCESS = 'GET_CATEGORY_ADMIN_SUCCESS';
export const GET_CATEGORY_ADMIN_FAIL = 'GET_CATEGORY_ADMIN_FAIL';