export const GET_COMMENT_PRODUCT_REQUEST = 'GET_COMMENT_PRODUCT_REQUEST';
export const GET_COMMENT_PRODUCT_SUCCESS = 'GET_COMMENT_PRODUCT_SUCCESS';
export const GET_COMMENT_PRODUCT_FAIL = 'GET_COMMENT_PRODUCT_FAIL';

export const POST_COMMENT_PRODUCT_REQUEST = 'POST_COMMENT_PRODUCT_REQUEST';
export const POST_COMMENT_PRODUCT_SUCCESS = 'POST_COMMENT_PRODUCT_SUCCESS';
export const POST_COMMENT_PRODUCT_FAIL = 'POST_COMMENT_PRODUCT_FAIL';
