const CREATE_CONFIG_REQUEST = 'CREATE_CONFIG_REQUEST';
const CREATE_CONFIG_SUCCESS = 'CREATE_CONFIG_SUCCESS';
const CREATE_CONFIG_FAIL = 'CREATE_CONFIG_FAIL';

const GET_CONFIG_REQUEST = 'GET_CONFIG_REQUEST';
const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';
const GET_CONFIG_FAIL = 'GET_CONFIG_FAIL';

const UPDATE_CONFIG_REQUEST = 'UPDATE_CONFIG_REQUEST';
const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS';
const UPDATE_CONFIG_FAIL = 'UPDATE_CONFIG_FAIL';
export default {
  CREATE_CONFIG_REQUEST,
  CREATE_CONFIG_SUCCESS,
  CREATE_CONFIG_FAIL,
  GET_CONFIG_REQUEST,
  GET_CONFIG_SUCCESS,
  GET_CONFIG_FAIL,
  UPDATE_CONFIG_REQUEST,
  UPDATE_CONFIG_SUCCESS,
  UPDATE_CONFIG_FAIL,
};
