export const CREATE_ADDRESS_NEW_REQUEST = 'CREATE_ADDRESS_NEW_REQUEST';
export const CREATE_ADDRESS_NEW_SUCCESS = 'CREATE_ADDRESS_NEW_SUCCESS';
export const CREATE_ADDRESS_NEW_FAIL = 'CREATE_ADDRESS_NEW_FAIL';

export const GET_LIST_ADDRESS_REQUEST = 'GET_LIST_ADDRESS_REQUEST';
export const GET_LIST_ADDRESS_SUCCESS = 'GET_LIST_ADDRESS_SUCCESS';
export const GET_LIST_ADDRESS_FAIL = 'GET_LIST_ADDRESS_FAIL';
