export const CREATE_ADDRESS_NEW_REQUEST = 'CREATE_ADDRESS_NEW_REQUEST';
export const CREATE_ADDRESS_NEW_SUCCESS = 'CREATE_ADDRESS_NEW_SUCCESS';
export const CREATE_ADDRESS_NEW_FAIL = 'CREATE_ADDRESS_NEW_FAIL';