export const ORDER_SAVE_REQUEST = 'ORDER_SAVE_REQUEST';
export const ORDER_SAVE_SUCCESS = 'ORDER_SAVE_SUCCESS';
export const ORDER_SAVE_FAIL = 'ORDER_SAVE_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_LIST_ADMIN_REQUEST = 'ORDER_LIST_ADMIN_REQUEST';
export const ORDER_LIST_ADMIN_SUCCESS = 'ORDER_LIST_ADMIN_SUCCESS';
export const ORDER_LIST_ADMIN_FAIL = 'ORDER_LIST_ADMIN_FAIL';