export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_ADMIN_LIST_REQUEST = 'PRODUCT_ADMIN_LIST_REQUEST';
export const PRODUCT_ADMIN_LIST_SUCCESS = 'PRODUCT_ADMIN_LIST_SUCCESS';
export const PRODUCT_ADMIN_LIST_FAIL = 'PRODUCT_ADMIN_LIST_FAIL';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';

export const PRODUCT_UPDATE_STATES_REQUEST = 'PRODUCT_UPDATE_STATES_REQUEST';
export const PRODUCT_UPDATE_STATES_SUCCESS = 'PRODUCT_UPDATE_STATES_SUCCESS';
export const PRODUCT_UPDATE_STATES_FAIL = 'PRODUCT_UPDATE_STATES_FAIL';



export const PRODUCT_REMOVE_REQUEST = 'PRODUCT_REMOVE_REQUEST';
export const PRODUCT_REMOVE_SUCCESS = 'PRODUCT_REMOVE_SUCCESS';
export const PRODUCT_REMOVE_FAIL = 'PRODUCT_REMOVE_FAIL';

export const PRODUCT_NEW_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_NEW_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_NEW_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_LIKE_REQUEST = 'PRODUCT_LIKE_REQUEST';
export const PRODUCT_LIKE_SUCCESS = 'PRODUCT_LIKE_SUCCESS';
export const PRODUCT_LIKE_FAIL = 'PRODUCT_LIKE_FAIL';
export const CHANGE_FIELDS = 'PRODUCT_CHANGE_FIELDS';
