const CREATE_STOCK_REQUEST = 'CREATE_STOCK_REQUEST';
const CREATE_STOCK_SUCCESS = 'CREATE_STOCK_SUCCESS';
const CREATE_STOCK_FAIL = 'CREATE_STOCK_FAIL';

const GET_STOCK_REQUEST = 'GET_STOCK_REQUEST';
const GET_STOCK_SUCCESS = 'GET_STOCK_SUCCESS';
const GET_STOCK_FAIL = 'GET_STOCK_FAIL';

const IMPORT_STOCK_REQUEST = 'IMPORT_STOCK_REQUEST';
const IMPORT_STOCK_SUCCESS = 'IMPORT_STOCK_SUCCESS';
const IMPORT_STOCK_FAIL = 'IMPORT_STOCK_FAIL';
const CHANGE_FIELDS = 'STOCK_CHANGE_FIELDS';
export default {
  CREATE_STOCK_REQUEST,
  CREATE_STOCK_SUCCESS,
  CREATE_STOCK_FAIL,
  GET_STOCK_REQUEST,
  GET_STOCK_SUCCESS,
  GET_STOCK_FAIL,
  IMPORT_STOCK_REQUEST,
  IMPORT_STOCK_SUCCESS,
  IMPORT_STOCK_FAIL,
  CHANGE_FIELDS,
};
