export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const UPDATE_INFO_REQUEST = 'UPDATE_INFO_REQUEST';
export const UPDATE_INFO_SUCCESS = 'UPDATE_INFO_SUCCESS';
export const UPDATE_INFO_FAIL = 'UPDATE_INFO_FAIL';

export const GET_FULL_INFO_REQUEST = 'GET_FULL_INFO_REQUEST';
export const GET_FULL_INFO_SUCCESS = 'GET_FULL_INFO_SUCCESS';
export const GET_FULL_INFO_FAIL = 'GET_FULL_INFO_FAIL';

export const CHANGE_PWD_REQUEST = 'CHANGE_PWD_REQUEST';
export const CHANGE_PWD_SUCCESS = 'CHANGE_PWD_SUCCESS';
export const CHANGE_PWD_FAIL = 'CHANGE_PWD_FAIL';
